_Created by Foxxy_

## Vì dữ liệu bao gồm khá nhiều file và chứa nhiều thông tin nên ta sẽ lần lượt khám phá và tiền xử lý dữ liệu để tạo 1 nguồn data "sạch" làm đầu vào cho công cụ __Tableau__

In [49]:
import pandas as pd
import numpy as np

In [50]:
df = pd.read_csv('..\\data\\raw\\ESGData.csv')
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Unnamed: 67
0,Arab World,ARB,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,86.557335,86.748192,86.928217,87.073901,87.127460,87.281663,87.291605,NaN,NaN,NaN
1,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,88.282060,88.891130,89.354222,90.446010,88.916243,90.007597,90.234390,NaN,NaN,NaN
2,Arab World,ARB,Adjusted savings: natural resources depletion ...,NY.ADJ.DRES.GN.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.253675,6.206522,5.176991,6.452049,8.444370,7.354977,4.354760,NaN,NaN,NaN
3,Arab World,ARB,Adjusted savings: net forest depletion (% of GNI),NY.ADJ.DFOR.GN.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.084391,0.099016,0.094321,0.095004,0.050844,0.061721,0.078484,NaN,NaN,NaN
4,Arab World,ARB,Agricultural land (% of land area),AG.LND.AGRI.ZS,NaN,30.981194,30.982443,31.006834,31.017781,31.042245,...,36.529508,36.565532,36.627752,36.673546,36.659112,36.597936,36.659647,NaN,NaN,NaN

# Lọc dữ liệu của Việt Nam

In [51]:
df_vn = df[df['Country Name'] == 'Vietnam']
df_vn

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Unnamed: 67
16685,Vietnam,VNM,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,58.300000,59.600000,61.000000,62.300000,63.300000,64.400000,65.300000,NaN,NaN,NaN
16686,Vietnam,VNM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.199997,99.821304,99.199997,100.000000,100.000000,99.400002,100.000000,NaN,NaN,NaN
16687,Vietnam,VNM,Adjusted savings: natural resources depletion ...,NY.ADJ.DRES.GN.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.912930,1.028119,0.715994,0.789160,0.805068,0.534177,0.246084,0.514637,NaN,NaN
16688,Vietnam,VNM,Adjusted savings: net forest depletion (% of GNI),NY.ADJ.DFOR.GN.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
16689,Vietnam,VNM,Agricultural land (% of land area),AG.LND.AGRI.ZS,NaN,19.330855,19.346216,19.361578,19.376939,19.392301,...,34.699127,38.763430,38.840794,38.827963,38.734450,39.524103,39.434768,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16751,Vietnam,VNM,Terrestrial and marine protected areas (% of t...,ER.PTD.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.929447,2.929507,2.929507,2.929507,2.929507,2.929507,2.929507,NaN
16752,Vietnam,VNM,Tree Cover Loss (hectares),AG.LND.FRLS.HA,NaN,NaN,NaN,NaN,NaN,NaN,...,217342.000000,217883.000000,353446.000000,286940.000000,225155.000000,216779.000000,207641.000000,193074.000000,NaN,NaN
16753,Vietnam,VNM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.260000,1.850000,1.850000,1.870000,1.160000,1.680000,2.100000,2.380000,1.923000,NaN
16754,Vietnam,VNM,Unmet need for contraception (% of married wom...,SP.UWT.TFRT,NaN,NaN,NaN,NaN,NaN,NaN,...,6.105270,NaN,NaN,NaN,NaN,NaN,NaN,10.100000,NaN,NaN
16755,Vietnam,VNM,Voice and Accountability: Estimate,VA.EST,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.374712,-1.358860,-1.373376,-1.411093,-1.476463,-1.405620,-1.378373,-1.304205,NaN,NaN

In [52]:
df_vn.drop(['Country Name', 'Country Code', 'Indicator Code', 'Unnamed: 67'], axis=1, inplace=True)
# df_vn.set_index('Indicator Name', inplace=True)
df_vn = df_vn.T.reset_index()
df_vn.rename(columns=df_vn.iloc[0], inplace=True)
df_vn = df_vn[1:].reset_index(drop=True)


df_vn.dropna(axis=1, how='all', inplace=True)
df_vn

C:\Users\Admin\AppData\Local\Temp\ipykernel_11976\702991492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vn.drop(['Country Name', 'Country Code', 'Indicator Code', 'Unnamed: 67'], axis=1, inplace=True)

,Indicator Name,Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),Adjusted savings: natural resources depletion (% of GNI),Adjusted savings: net forest depletion (% of GNI),Agricultural land (% of land area),"Agriculture, forestry, and fishing, value added (% of GDP)","Annual freshwater withdrawals, total (% of internal resources)","Annualized average growth rate in per capita real survey mean consumption or income, total population (%)","Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)",...,"School enrollment, primary (% gross)","School enrollment, primary and secondary (gross), gender parity index (GPI)",Scientific and technical journal articles,Standardised Precipitation-Evapotranspiration Index,Strength of legal rights index (0=weak to 12=strong),Terrestrial and marine protected areas (% of total territorial area),Tree Cover Loss (hectares),"Unemployment, total (% of total labor force) (modeled ILO estimate)",Unmet need for contraception (% of married women ages 15-49),Voice and Accountability: Estimate
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1961,NaN,NaN,NaN,NaN,19.330855,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1962,NaN,NaN,NaN,NaN,19.346216,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1963,NaN,NaN,NaN,NaN,19.361578,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1964,NaN,NaN,NaN,NaN,19.376939,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,2018,63.3,100.0,0.805068,0.0,38.73445,12.306675,22.776139,NaN,NaN,...,110.59481,NaN,4088.91,NaN,8.0,2.929507,225155.0,1.16,NaN,-1.476463
59,2019,64.4,99.400002,0.534177,0.0,39.524103,11.784526,22.776139,NaN,9.304941,...,115.435173,NaN,5812.63,NaN,8.0,2.929507,216779.0,1.68,NaN,-1.40562
60,2020,65.3,100.0,0.246084,0.0,39.434768,12.655397,22.776139,5.61,NaN,...,117.157173,NaN,8213.16,NaN,NaN,2.929507,207641.0,2.1,NaN,-1.378373
61,2021,NaN,NaN,0.514637,0.0,NaN,12.560364,NaN,NaN,NaN,...,118.430527,NaN,NaN,NaN,NaN,2.929507,193074.0,2.38,10.1,-1.304205
62,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.929507,NaN,1.923,NaN,NaN

In [53]:
df_vn.describe()

,Indicator Name,Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),Adjusted savings: natural resources depletion (% of GNI),Adjusted savings: net forest depletion (% of GNI),Agricultural land (% of land area),"Agriculture, forestry, and fishing, value added (% of GDP)","Annual freshwater withdrawals, total (% of internal resources)","Annualized average growth rate in per capita real survey mean consumption or income, total population (%)","Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)",...,"School enrollment, primary (% gross)","School enrollment, primary and secondary (gross), gender parity index (GPI)",Scientific and technical journal articles,Standardised Precipitation-Evapotranspiration Index,Strength of legal rights index (0=weak to 12=strong),Terrestrial and marine protected areas (% of total territorial area),Tree Cover Loss (hectares),"Unemployment, total (% of total labor force) (modeled ILO estimate)",Unmet need for contraception (% of married women ages 15-49),Voice and Accountability: Estimate
count,63,21.0,24.0,33.000000,33.0,60.000000,36.000000,41.000000,1.00,4.000000,...,45.000000,3.00000,25.0,20.0,7.0,7.000000,20.0,32.00,5.0,23.000000
unique,63,21.0,20.0,33.000000,1.0,59.000000,36.000000,26.000000,1.00,4.000000,...,45.000000,3.00000,25.0,4.0,2.0,4.000000,20.0,31.00,5.0,23.000000
top,1960,14.0,100.0,2.359326,0.0,20.615073,38.063439,22.776139,5.61,18.126715,...,109.960991,1.02029,178.4,0.0,7.0,2.929507,49625.0,1.85,8.4,-1.087494
freq,1,1.0,3.0,1.000000,33.0,2.000000,1.000000,16.000000,1.00,1.000000,...,1.000000,1.00000,1.0,11.0,4.0,2.000000,1.0,2.00,1.0,1.000000

In [54]:
df_vn.to_excel('../data/processed/ESGData_VN.xlsx')

In [55]:
new_df = df.copy()
# Extract the year values from the column headers
year_cols = [col for col in new_df.columns if col.isnumeric()]

# Define the columns to keep as identifiers
id_vars = ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code']

# Pivot the value columns into a single column
new_df = new_df.melt(id_vars=id_vars, value_vars=year_cols, var_name='Year', value_name='Value')

# Display the pivoted data
display(new_df)

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value
0,Arab World,ARB,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,1960,NaN
1,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,1960,NaN
2,Arab World,ARB,Adjusted savings: natural resources depletion ...,NY.ADJ.DRES.GN.ZS,1960,NaN
3,Arab World,ARB,Adjusted savings: net forest depletion (% of GNI),NY.ADJ.DFOR.GN.ZS,1960,NaN
4,Arab World,ARB,Agricultural land (% of land area),AG.LND.AGRI.ZS,1960,NaN
...,...,...,...,...,...,...
1069042,Zimbabwe,ZWE,Terrestrial and marine protected areas (% of t...,ER.PTD.TOTL.ZS,2022,27.214747
1069043,Zimbabwe,ZWE,Tree Cover Loss (hectares),AG.LND.FRLS.HA,2022,NaN
1069044,Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2022,7.945000
1069045,Zimbabwe,ZWE,Unmet need for contraception (% of married wom...,SP.UWT.TFRT,2022,NaN
1069046,Zimbabwe,ZWE,Voice and Accountability: Estimate,VA.EST,2022,NaN

In [56]:
new_df.to_csv('../data/processed//ESGData_processed.csv')

Dữ liệu sau khi được xử lý sẽ có số chiều bằng với số chiều ban đầu

In [57]:
print(new_df.shape[0] == df.shape[0] * 63)

True

## Lọc dữ liệu region và 1 số aggregation ra 1 file khác

In [58]:
countries_df = pd.read_csv('..\\data\\raw\\ESGCountry.csv')

- Các nước không có đơn vị tiền tệ:

In [59]:
countries_df['Special Notes'].str.contains('aggregate', na=False).sum()
countries_df['Currency Unit'].isna().sum()

46

- Các nước không có đơn vị tiền tệ là các group aggregation trong dataset, ta sẽ lọc các giá trị này ra 1 dataset khác

In [60]:
countries_code_sr = countries_df[countries_df['Currency Unit'].notna()]['Country Code']
countries_code_sr

0      AFG
1      AGO
2      ALB
3      AND
5      ARE
      ...
234    WSM
235    YEM
236    ZAF
237    ZMB
238    ZWE
Name: Country Code, Length: 193, dtype: object

In [61]:
agg_df = new_df[~new_df['Country Code'].isin(countries_code_sr)]
agg_df = agg_df[agg_df['Value'].notnull()]

grouped = agg_df.groupby(['Country Name', 'Indicator Name']).agg({'Value': 'count'})
grouped = grouped[grouped['Value'] > 0]
grouped = grouped.reset_index()
agg_df = pd.merge(agg_df, grouped[['Country Name', 'Indicator Name']], on=['Country Name', 'Indicator Name'])

agg_df

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value
0,Arab World,ARB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,1960,6.934332
1,Arab World,ARB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,1961,6.982115
2,Arab World,ARB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,1962,7.076112
3,Arab World,ARB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,1963,7.071542
4,Arab World,ARB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,1964,7.061969
...,...,...,...,...,...,...
68163,South Asia (IDA & IBRD),TSA,"Mammal species, threatened",EN.MAM.THRD.NO,2018,252.000000
68164,Sub-Saharan Africa,SSF,"Mammal species, threatened",EN.MAM.THRD.NO,2018,967.000000
68165,Sub-Saharan Africa (excluding high income),SSA,"Mammal species, threatened",EN.MAM.THRD.NO,2018,961.000000
68166,Sub-Saharan Africa (IDA & IBRD),TSS,"Mammal species, threatened",EN.MAM.THRD.NO,2018,967.000000
68167,Upper middle income,UMC,"Mammal species, threatened",EN.MAM.THRD.NO,2018,980.000000

In [62]:
series_df = pd.read_csv('..\\data\\raw\\ESGSeries.csv')
field_df = series_df[['Series Code', 'Topic']]
agg_df = pd.merge(agg_df, field_df, left_on='Indicator Code', right_on='Series Code', how='left')
agg_df.drop(['Series Code', 'Indicator Code'], axis=1, inplace=True)
agg_df.to_csv('..\\data\\processed\\ESGData_agg.csv')

# Lọc data theo 3 chủ đề chính: Environment, Social, Governance

In [63]:
new_df = new_df[new_df['Country Code'].isin(countries_code_sr)]

## Concat 2 table ESGSeries và ESGData sau khi đã tiền xử lý

In [64]:
series_df = pd.read_csv('..\\data\\raw\\ESGSeries.csv')
series_df.head()

,Series Code,Topic,Indicator Name,Short definition,Long definition,Unit of measure,Periodicity,Base Period,Other notes,Aggregation method,...,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type,Unnamed: 20
0,AG.LND.AGRI.ZS,Environment: Food Security,Agricultural land (% of land area),NaN,Agricultural land refers to the share of land ...,NaN,Annual,NaN,Areas of former states are included in the suc...,Weighted average,...,NaN,NaN,"Food and Agriculture Organization, electronic ...",Agriculture is still a major sector in many ec...,Agricultural land covers more than one-third o...,NaN,NaN,NaN,CC BY-4.0,NaN
1,AG.LND.FRLS.HA,Environment: Natural capital endowment and man...,Tree Cover Loss,Identifies areas of gross tree cover loss.,"Shows year-by-year tree cover loss, defined as...",Hectares,Annual,NaN,Administrative boundaries: Global Administrati...,Weighted average,...,NaN,"In this data set, “tree cover” is defined as a...",Global Forest Watch. Tree Cover Loss (Hansen/U...,NaN,NaN,https://data.globalforestwatch.org/maps/gfw::t...,https://data.globalforestwatch.org/pages/data-...,NaN,CC BY-4.0,NaN
2,AG.LND.FRST.ZS,Environment: Natural capital endowment and man...,Forest area (% of land area),NaN,Forest area is land under natural or planted s...,NaN,Annual,NaN,Areas of former states are included in the suc...,Weighted average,...,NaN,NaN,"Food and Agriculture Organization, electronic ...",Forest is determined both by the presence of t...,"As threats to biodiversity mount, the internat...",NaN,NaN,NaN,CC BY-4.0,NaN
3,AG.PRD.FOOD.XD,Environment: Food Security,Food production index (2014-2016 = 100),NaN,Food production index covers food crops that a...,NaN,Annual,2014-16,NaN,Weighted average,...,NaN,NaN,"Food and Agriculture Organization, electronic ...",The agricultural production index is prepared ...,The commodities covered in the computation of ...,NaN,NaN,NaN,CC BY-4.0,NaN
4,CC.EST,Governance: Stability & Rule of Law,Control of Corruption: Estimate,NaN,Control of Corruption captures perceptions of ...,NaN,Annual,NaN,NaN,NaN,...,NaN,NaN,"Detailed documentation of the WGI, interactive...",NaN,NaN,NaN,NaN,NaN,CC BY-4.0,NaN

In [65]:
new_df.drop('Country Code', axis=1, inplace=True)
field_df = series_df[['Series Code', 'Topic']]
new_df = pd.merge(new_df, field_df, left_on='Indicator Code', right_on='Series Code', how='left')
new_df.drop(['Series Code', 'Indicator Code'], axis=1, inplace=True)
new_df

,Country Name,Indicator Name,Year,Value,Topic
0,Afghanistan,Access to clean fuels and technologies for coo...,1960,NaN,Social: Access to Services
1,Afghanistan,Access to electricity (% of population),1960,NaN,Social: Access to Services
2,Afghanistan,Adjusted savings: natural resources depletion ...,1960,NaN,Environment: Natural capital endowment and man...
3,Afghanistan,Adjusted savings: net forest depletion (% of GNI),1960,NaN,Environment: Natural capital endowment and man...
4,Afghanistan,Agricultural land (% of land area),1960,NaN,Environment: Food Security
...,...,...,...,...,...
863284,Zimbabwe,Terrestrial and marine protected areas (% of t...,2022,27.214747,Environment: Natural capital endowment and man...
863285,Zimbabwe,Tree Cover Loss (hectares),2022,NaN,Environment: Natural capital endowment and man...
863286,Zimbabwe,"Unemployment, total (% of total labor force) (...",2022,7.945000,Social: Employment
863287,Zimbabwe,Unmet need for contraception (% of married wom...,2022,NaN,Governance: Gender
863288,Zimbabwe,Voice and Accountability: Estimate,2022,NaN,Governance: Human Rights

## Chọn ra các dữ liệu thuộc Environment

In [66]:
def filter(field):
    return new_df[new_df['Topic'].str.contains(field, na=False)]
env_df = filter('Environment:')
env_df

,Country Name,Indicator Name,Year,Value,Topic
2,Afghanistan,Adjusted savings: natural resources depletion ...,1960,NaN,Environment: Natural capital endowment and man...
3,Afghanistan,Adjusted savings: net forest depletion (% of GNI),1960,NaN,Environment: Natural capital endowment and man...
4,Afghanistan,Agricultural land (% of land area),1960,NaN,Environment: Food Security
5,Afghanistan,"Agriculture, forestry, and fishing, value adde...",1960,NaN,Environment: Food Security
6,Afghanistan,"Annual freshwater withdrawals, total (% of int...",1960,NaN,Environment: Natural capital endowment and man...
...,...,...,...,...,...
863275,Zimbabwe,Renewable electricity output (% of total elect...,2022,NaN,Environment: Energy use & security
863276,Zimbabwe,Renewable energy consumption (% of total final...,2022,NaN,Environment: Energy use & security
863282,Zimbabwe,Standardised Precipitation-Evapotranspiration ...,2022,NaN,Environment: Environment/climate risk & resili...
863284,Zimbabwe,Terrestrial and marine protected areas (% of t...,2022,27.214747,Environment: Natural capital endowment and man...
863285,Zimbabwe,Tree Cover Loss (hectares),2022,NaN,Environment: Natural capital endowment and man...

In [67]:
env_df.to_csv('..\\data\\processed\\ESGData_environment_processed.csv')

## Chọn ra các dữ liệu thuộc Social

In [68]:
so_df = filter('Social:')
country_df = pd.read_csv('..\\data\\raw\\ESGCountry.csv')
so_df = pd.merge(so_df, country_df, left_on='Country Name', right_on='Short Name', how='left')

drop_cols = [
    'Short Name', 'Table Name', 'Long Name', '2-alpha code', 'Unnamed: 30', 'Special Notes',
    'Latest population census',	'Latest household survey','Source of most recent Income and expenditure data',
    'Vital registration complete', 'Latest agricultural census', 'Latest industrial data',	
    'Latest trade data'
]

so_df.drop(drop_cols, axis=1, inplace=True)
so_df

,Country Name,Indicator Name,Year,Value,Topic,Country Code,Currency Unit,Region,Income Group,WB-2 code,...,Lending category,Other groups,System of National Accounts,Alternative conversion factor,PPP survey year,Balance of Payments Manual in use,External debt Reporting status,System of trade,Government Accounting concept,IMF data dissemination standard
0,Afghanistan,Access to clean fuels and technologies for coo...,1960,NaN,Social: Access to Services,AFG,Afghan afghani,South Asia,Low income,AF,...,IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,NaN,BPM6,Estimate,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...
1,Afghanistan,Access to electricity (% of population),1960,NaN,Social: Access to Services,AFG,Afghan afghani,South Asia,Low income,AF,...,IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,NaN,BPM6,Estimate,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...
2,Afghanistan,Annualized average growth rate in per capita r...,1960,NaN,Social: Poverty & Inequality,AFG,Afghan afghani,South Asia,Low income,AF,...,IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,NaN,BPM6,Estimate,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...
3,Afghanistan,"Cause of death, by communicable diseases and m...",1960,NaN,Social: Health & Nutrition,AFG,Afghan afghani,South Asia,Low income,AF,...,IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,NaN,BPM6,Estimate,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...
4,Afghanistan,"Children in employment, total (% of children a...",1960,NaN,Social: Employment,AFG,Afghan afghani,South Asia,Low income,AF,...,IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,NaN,BPM6,Estimate,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267493,Zimbabwe,Poverty headcount ratio at national poverty li...,2022,NaN,Social: Poverty & Inequality,ZWE,Zimbabwean Dollar,Sub-Saharan Africa,Lower middle income,ZW,...,Blend,NaN,Country uses the 2008 System of National Accou...,NaN,NaN,BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...
267494,Zimbabwe,Prevalence of overweight (% of adults),2022,NaN,Social: Health & Nutrition,ZWE,Zimbabwean Dollar,Sub-Saharan Africa,Lower middle income,ZW,...,Blend,NaN,Country uses the 2008 System of National Accou...,NaN,NaN,BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...
267495,Zimbabwe,Prevalence of undernourishment (% of population),2022,NaN,Social: Health & Nutrition,ZWE,Zimbabwean Dollar,Sub-Saharan Africa,Lower middle income,ZW,...,Blend,NaN,Country uses the 2008 System of National Accou...,NaN,NaN,BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...
267496,Zimbabwe,"School enrollment, primary (% gross)",2022,NaN,Social: Education & skills,ZWE,Zimbabwean Dollar,Sub-Saharan Africa,Lower middle income,ZW,...,Blend,NaN,Country uses the 2008 System of National Accou...,NaN,NaN,BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...
267497,Zimbabwe,"Unemployment, total (% of total labor force) (...",2022,7.945,Social: Employment,ZWE,Zimbabwean Dollar,Sub-Saharan Africa,Lower middle income,ZW,...,Blend,NaN,Country uses the 2008 System of National Accou...,NaN,NaN,BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...

In [69]:
so_df.to_csv('..\\data\\processed\\ESGData_social_processed.csv', index=False)

## Chọn ra các dữ liệu thuộc Governance

In [70]:
gor_df = filter('Governance:')
gor_df

,Country Name,Indicator Name,Year,Value,Topic
12,Afghanistan,Control of Corruption: Estimate,1960,NaN,Governance: Stability & Rule of Law
14,Afghanistan,Economic and Social Rights Performance Score,1960,NaN,Governance: Human Rights
23,Afghanistan,GDP growth (annual %),1960,NaN,Governance: Economic Environment
26,Afghanistan,Government Effectiveness: Estimate,1960,NaN,Governance: Government Effectiveness
32,Afghanistan,Individuals using the Internet (% of population),1960,NaN,Governance: Economic Environment
...,...,...,...,...,...
863280,Zimbabwe,"School enrollment, primary and secondary (gros...",2022,NaN,Governance: Gender
863281,Zimbabwe,Scientific and technical journal articles,2022,NaN,Governance: Innovation
863283,Zimbabwe,Strength of legal rights index (0=weak to 12=s...,2022,NaN,Governance: Human Rights
863287,Zimbabwe,Unmet need for contraception (% of married wom...,2022,NaN,Governance: Gender
863288,Zimbabwe,Voice and Accountability: Estimate,2022,NaN,Governance: Human Rights

In [71]:
gor_df.to_csv('..\\data\\processed\\ESGData_governance_processed.csv')